-- ==========================================================================
-- LINKO — consolidated schema snapshot
--
-- Final state after migrations 001..024. Generated by hand from the migration
-- files, not from a pgAdmin dump: it includes the CHECK constraints, triggers,
-- functions, partial unique indexes, sequence, and category seed rows that a
-- table-only dump loses.
--
-- WHAT THIS IS FOR
--   Reference / ERD source / fresh throwaway database. It is NOT the source of
--   truth — backend/migrations/ is. Do not edit a migration to match this file;
--   add a new migration and regenerate this one.
--
-- HOW TO USE ON A FRESH DATABASE
--   psql "$DATABASE_URL" -f backend/schema.sql
--   This also stamps schema_migrations with 001..024, so a later
--   `npm run migrate` picks up only NEW files instead of replaying everything.
--
-- WHAT IS DEFINITELY NOT HERE
--   - Phased-out objects: inventory_items, inventory_transactions (019),
--     commissions, commission_brackets, wholesaler_remittances view (018).
--   - Data-only migrations: 012 (tracking branch backfill) and 014 (parcel
--     pricing repair) operate on rows that do not exist in a fresh DB.
--   - Demo data: see backend/seeds/dev_seed.sql. Only the 12 canonical
--     categories are seeded here, because migration 005 seeds them as schema.
-- ==========================================================================

BEGIN;

-- ==========================================================================
-- SECTION 0 — Empty-database guard
--
-- This file builds a schema from scratch; it is NOT an upgrade script and has
-- no rollback path. Run against a database that already has LINKO tables and
-- the first CREATE TABLE fails with 42P07, which aborts the transaction and
-- makes every following statement report the confusing
--   ERROR: current transaction is aborted, commands ignored until end of
--   transaction block (SQL state 25P02)
-- ...which is what most clients surface, hiding the real cause.
--
-- Fail immediately with a message that says what to actually do instead.
-- ==========================================================================

DO $guard$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_tables
         WHERE schemaname = 'public'
           AND tablename IN ('users', 'businesses', 'parcels', 'orders')
    ) THEN
        RAISE EXCEPTION
            'Refusing to run: this database already has LINKO tables.'
            USING HINT =
                'schema.sql only builds a FRESH database. To upgrade an '
                'existing one, run `npm run migrate` instead. To rebuild this '
                'one from scratch, drop and recreate the database first '
                '(destroys all data).';
    END IF;
END
$guard$;

-- ==========================================================================
-- SECTION 1 — Identity & organizations
-- ==========================================================================

CREATE TABLE users (
    user_id       SERIAL PRIMARY KEY,
    username      VARCHAR(50) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    email         VARCHAR(100) NOT NULL UNIQUE,
    full_name     VARCHAR(100) NOT NULL,                       -- 004
    role          VARCHAR(20) NOT NULL
        CHECK (role IN ('owner', 'staff', 'wholesaler', 'admin')),
    global_role   VARCHAR(20),                                 -- 004
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,               -- 011
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_global_role_check
        CHECK (global_role IS NULL OR global_role = 'platform_admin')
);

-- business_type: 'both' removed in 017 (one marketplace role per business);
-- 'logistics' added in 022 for the canonical LINKO Logistics org.
CREATE TABLE businesses (
    business_id          SERIAL PRIMARY KEY,
    business_name        VARCHAR(100) NOT NULL,
    business_type        VARCHAR(20) NOT NULL,
    contact_number       VARCHAR(20),
    is_verified          BOOLEAN DEFAULT FALSE,
    logistics_address_id INT,                                  -- 024, FK added below
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT businesses_business_type_check
        CHECK (business_type IN ('buyer', 'wholesaler', 'individual',
                                 'msme', 'corporation', 'other', 'logistics'))
);

-- Legacy user<->business link from 001. business_memberships is the RBAC
-- source of truth; this survives as the plain ownership join.
CREATE TABLE user_businesses (
    user_id     INT REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    business_id INT REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE CASCADE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,           -- 010
    PRIMARY KEY (user_id, business_id)
);

CREATE TABLE business_memberships (
    membership_id SERIAL PRIMARY KEY,
    user_id       INT NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    business_id   INT NOT NULL REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE CASCADE,
    role          VARCHAR(30) NOT NULL
        CHECK (role IN ('buyer', 'wholesaler', 'logistics_coordinator', 'courier')),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, business_id, role)
);

CREATE TABLE auth_sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    user_id    INT NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Philippine address hierarchy. business_id NULL = ownerless (branch addresses).
-- Coordinates are WGS84 decimal degrees: paired, in range, never Null Island.
CREATE TABLE addresses (
    address_id        SERIAL PRIMARY KEY,
    business_id       INT REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE SET NULL,
    province          VARCHAR(50) NOT NULL,
    city_municipality VARCHAR(50) NOT NULL,
    barangay          VARCHAR(50),
    street_address    VARCHAR(150),
    postal_code       VARCHAR(10),
    latitude          DECIMAL(10,7),                           -- 023
    longitude         DECIMAL(10,7),                           -- 023
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     -- 010
    -- 024
    CONSTRAINT addresses_coords_paired
        CHECK ((latitude IS NULL) = (longitude IS NULL)),
    CONSTRAINT addresses_latitude_range
        CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT addresses_longitude_range
        CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT addresses_no_null_island
        CHECK (latitude <> 0 OR longitude <> 0)
);

-- Deferred to break the businesses <-> addresses cycle.
ALTER TABLE businesses
    ADD CONSTRAINT businesses_logistics_address_id_fkey
    FOREIGN KEY (logistics_address_id) REFERENCES addresses(address_id)
    ON UPDATE CASCADE ON DELETE SET NULL;

-- ==========================================================================
-- SECTION 2 — Marketplace catalog
-- ==========================================================================

CREATE TABLE categories (
    category_id   SERIAL PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL UNIQUE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP          -- 010
);

CREATE TABLE warehouses (
    warehouse_id   SERIAL PRIMARY KEY,
    business_id    INT NOT NULL REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    warehouse_name VARCHAR(100) NOT NULL,
    address_id     INT NOT NULL REFERENCES addresses(address_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP          -- 010
);

-- sku is optional (005) and unique only among ACTIVE rows, so a soft-deleted
-- product's sku is reusable.
CREATE TABLE products (
    product_id     SERIAL PRIMARY KEY,
    business_id    INT NOT NULL REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    product_name   VARCHAR(100) NOT NULL,
    sku            VARCHAR(50),
    category_id    INT REFERENCES categories(category_id) ON UPDATE CASCADE ON DELETE SET NULL,
    description    TEXT,
    unit_price     NUMERIC(12,2) NOT NULL DEFAULT 0,           -- 005
    image_url      TEXT,                                       -- 005
    stock_quantity INTEGER NOT NULL DEFAULT 0,                 -- 005
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,              -- 005
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,        -- 010
    CONSTRAINT products_unit_price_check     CHECK (unit_price >= 0),
    CONSTRAINT products_stock_quantity_check CHECK (stock_quantity >= 0)
);

CREATE TABLE supplier_profiles (
    supplier_id            INT PRIMARY KEY REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE CASCADE,
    minimum_order_quantity DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    lead_time_days         INT NOT NULL DEFAULT 7 CHECK (lead_time_days >= 0),
    delivery_terms         TEXT,
    trust_rating           DECIMAL(3,2) DEFAULT 5.00
        CHECK (trust_rating >= 0.00 AND trust_rating <= 5.00),
    verification_status    VARCHAR(20) DEFAULT 'pending'
        CHECK (verification_status IN ('pending', 'verified', 'rejected')),
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- 010
);

-- ==========================================================================
-- SECTION 3 — Logistics core (CIS 2104 graded tables)
-- ==========================================================================

-- Shipping fee formula inputs: base_fee + weight*base_rate_per_kg + km*rate_per_km.
CREATE TABLE service_tiers (
    tier_id          SERIAL PRIMARY KEY,
    tier_name        VARCHAR(50) NOT NULL UNIQUE,
    base_rate_per_kg DECIMAL(10,2) NOT NULL,
    estimated_days   INT NOT NULL,
    base_fee         DECIMAL(10,2) NOT NULL,                   -- 003
    rate_per_km      DECIMAL(10,2) NOT NULL                    -- 003
);

-- branch_name uniqueness is partial (active rows only, 016) so a soft-deleted
-- name can be reused.
CREATE TABLE branches (
    branch_id      SERIAL PRIMARY KEY,
    branch_name    VARCHAR(100) NOT NULL,
    address_id     INT NOT NULL REFERENCES addresses(address_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    contact_number VARCHAR(20),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,              -- 015
    is_available   BOOLEAN NOT NULL DEFAULT TRUE               -- 023 auto-assign toggle
);

CREATE TABLE couriers (
    courier_id         SERIAL PRIMARY KEY,
    full_name          VARCHAR(100) NOT NULL,
    phone_number       VARCHAR(20),                            -- nullable since 009
    vehicle_type       VARCHAR(30),
    assigned_branch_id INT REFERENCES branches(branch_id) ON UPDATE CASCADE ON DELETE SET NULL,
    user_id            INT REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,  -- 008
    is_active          BOOLEAN NOT NULL DEFAULT TRUE           -- 015
);

-- ==========================================================================
-- SECTION 4 — Marketplace orders
-- ==========================================================================

CREATE TABLE orders (
    order_id               SERIAL PRIMARY KEY,
    buyer_business_id      INT NOT NULL REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    wholesaler_business_id INT NOT NULL REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    tier_id                INT NOT NULL REFERENCES service_tiers(tier_id) ON UPDATE CASCADE ON DELETE RESTRICT,  -- 007
    status                 VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_by             INT REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 'returned' added in 013
    CONSTRAINT orders_status_check
        CHECK (status IN ('pending', 'accepted', 'preparing', 'shipped',
                          'delivered', 'cancelled', 'returned'))
);

CREATE TABLE order_items (
    order_item_id       SERIAL PRIMARY KEY,
    order_id            INT NOT NULL REFERENCES orders(order_id) ON UPDATE CASCADE ON DELETE CASCADE,
    product_id          INT NOT NULL REFERENCES products(product_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    quantity            INT NOT NULL CHECK (quantity > 0),
    unit_price_snapshot NUMERIC(12,2) NOT NULL CHECK (unit_price_snapshot >= 0),
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoices (
    invoice_id     SERIAL PRIMARY KEY,
    order_id       INT NOT NULL UNIQUE REFERENCES orders(order_id) ON UPDATE CASCADE ON DELETE CASCADE,
    invoice_number VARCHAR(40) NOT NULL UNIQUE,
    total          NUMERIC(12,2) NOT NULL CHECK (total >= 0),
    issued_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP          -- 010
);

-- ==========================================================================
-- SECTION 5 — Parcels, payments, tracking
-- ==========================================================================

-- order_id NULL = standalone booking (BookParcel flow) with no marketplace order.
-- shipping_fee is derived-but-stored so historical pricing survives tier changes.
CREATE TABLE parcels (
    parcel_id              VARCHAR(20) PRIMARY KEY,
    sender_id              INT NOT NULL REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    receiver_id            INT NOT NULL REFERENCES businesses(business_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    tier_id                INT NOT NULL REFERENCES service_tiers(tier_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    origin_address_id      INT NOT NULL REFERENCES addresses(address_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    destination_address_id INT NOT NULL REFERENCES addresses(address_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    order_id               INT REFERENCES orders(order_id) ON UPDATE CASCADE ON DELETE SET NULL,  -- 009
    weight_kg              DECIMAL(6,2) NOT NULL CHECK (weight_kg > 0),
    dimensions             VARCHAR(50),
    shipping_fee           DECIMAL(10,2),                      -- renamed from total_cost in 003
    declared_value         DECIMAL(12,2) NOT NULL DEFAULT 0    -- 003, goods total
        CHECK (declared_value >= 0),
    total_distance_km      DECIMAL(8,2),
    estimated_delivery_date DATE
);

-- 1:1 with parcel. amount = declared_value + shipping_fee (buyer's total).
-- payment_status is the dispatch gate: modeled, NOT enforced in the DB.
CREATE TABLE payments (
    payment_id     SERIAL PRIMARY KEY,
    parcel_id      VARCHAR(20) NOT NULL UNIQUE REFERENCES parcels(parcel_id) ON UPDATE CASCADE ON DELETE CASCADE,
    method         VARCHAR(20) NOT NULL
        CHECK (method IN ('COD', 'Prepaid', 'Online')),
    payment_status VARCHAR(20) NOT NULL
        CHECK (payment_status IN ('Pending', 'Paid', 'Failed', 'Refunded')),
    amount         DECIMAL(12,2) NOT NULL,                     -- widened in 003
    paid_at        TIMESTAMP
);

-- Append-only scan history; current status = latest row by scanned_at.
-- 'In Transit' was removed in 020 (branch checkpoints carry that meaning).
CREATE TABLE tracking_logs (
    log_id        SERIAL PRIMARY KEY,
    parcel_id     VARCHAR(20) NOT NULL REFERENCES parcels(parcel_id) ON UPDATE CASCADE ON DELETE CASCADE,
    branch_id     INT REFERENCES branches(branch_id) ON UPDATE CASCADE ON DELETE SET NULL,
    courier_id    INT REFERENCES couriers(courier_id) ON UPDATE CASCADE ON DELETE SET NULL,
    status_update VARCHAR(50) NOT NULL,
    remarks       TEXT,
    scanned_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- final vocabulary after 020 + 021
    CONSTRAINT tracking_logs_status_update_check
        CHECK (status_update IN ('Order Created', 'Picked Up', 'Arrived at Branch',
                                 'Departed Branch', 'Out for Delivery', 'Delivery Failed',
                                 'Out for Return', 'Delivered', 'Returned', 'Cancelled'))
);

-- Immutable planned-route snapshot (origin -> branch -> destination). Text and
-- coordinates are COPIES, not joins: re-pinning a business must not rewrite
-- history. Display-only; actual tracking diverges freely.
CREATE TABLE parcel_route_stops (
    parcel_id         VARCHAR(20) NOT NULL REFERENCES parcels(parcel_id) ON UPDATE CASCADE ON DELETE CASCADE,
    stop_order        SMALLINT NOT NULL CHECK (stop_order BETWEEN 1 AND 3),
    stop_type         VARCHAR(20) NOT NULL CHECK (stop_type IN ('origin', 'branch', 'destination')),
    source_address_id INT REFERENCES addresses(address_id) ON UPDATE CASCADE ON DELETE SET NULL,
    branch_id         INT REFERENCES branches(branch_id) ON UPDATE CASCADE,
    label             VARCHAR(150) NOT NULL,
    province          VARCHAR(50),
    city_municipality VARCHAR(50),
    barangay          VARCHAR(50),
    street_address    VARCHAR(150),
    postal_code       VARCHAR(10),
    latitude          NUMERIC(10,7),
    longitude         NUMERIC(10,7),
    PRIMARY KEY (parcel_id, stop_order)
);

-- ==========================================================================
-- SECTION 6 — Functions & triggers
-- ==========================================================================

-- Derived-but-stored shipping fee, computed only when the caller supplied
-- none, so backfills and manual overrides win. NULL distance contributes zero.
CREATE FUNCTION fn_set_parcel_shipping_fee()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.shipping_fee IS NULL THEN
        SELECT st.base_fee
               + NEW.weight_kg * st.base_rate_per_kg
               + COALESCE(NEW.total_distance_km, 0) * st.rate_per_km
          INTO NEW.shipping_fee
          FROM service_tiers st
         WHERE st.tier_id = NEW.tier_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_parcel_shipping_fee
BEFORE INSERT ON parcels
FOR EACH ROW
EXECUTE FUNCTION fn_set_parcel_shipping_fee();

-- Buyer's total outlay, frozen from the parcel at booking time.
CREATE FUNCTION fn_set_payment_amount()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.amount IS NULL THEN
        SELECT p.declared_value + COALESCE(p.shipping_fee, 0)
          INTO NEW.amount
          FROM parcels p
         WHERE p.parcel_id = NEW.parcel_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_payment_amount
BEFORE INSERT ON payments
FOR EACH ROW
EXECUTE FUNCTION fn_set_payment_amount();

-- ==========================================================================
-- SECTION 7 — Notifications
-- ==========================================================================

CREATE TABLE notifications (
    notification_id SERIAL PRIMARY KEY,
    user_id         INT NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    title           VARCHAR(150) NOT NULL,
    message         TEXT NOT NULL,
    type            VARCHAR(50) DEFAULT 'info'
        CHECK (type IN ('info', 'success', 'warning', 'error')),
    is_read         BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================================
-- SECTION 8 — Sequences
-- ==========================================================================

-- Collision-proof parcel IDs (016). Replaces app-side `LKO-${Date.now()}`,
-- which collided under concurrent bookings.
CREATE SEQUENCE parcel_id_seq;

-- ==========================================================================
-- SECTION 9 — Indexes
--
-- PARTIAL UNIQUE indexes are load-bearing business rules, not tuning:
-- a plain index here silently drops the constraint.
-- ==========================================================================

-- Unique: reusable-after-soft-delete identifiers.
CREATE UNIQUE INDEX products_sku_active_uq
    ON products (sku) WHERE is_active AND sku IS NOT NULL;                  -- 005
CREATE UNIQUE INDEX uq_branches_name_active
    ON branches (branch_name) WHERE is_active;                              -- 016
CREATE UNIQUE INDEX uq_couriers_user_active
    ON couriers (user_id) WHERE user_id IS NOT NULL AND is_active;          -- 016

-- Unique: one marketplace role per (user, business) — the 017 'both' phase-out.
CREATE UNIQUE INDEX one_marketplace_role_per_business
    ON business_memberships (user_id, business_id)
    WHERE role IN ('buyer', 'wholesaler');                                  -- 017

-- Lookup indexes.
CREATE INDEX idx_products_sku                     ON products (sku);
CREATE INDEX idx_products_business_active         ON products (business_id) WHERE is_active;
CREATE INDEX idx_products_category                ON products (category_id);
CREATE INDEX idx_business_memberships_business_role ON business_memberships (business_id, role);
CREATE INDEX idx_auth_sessions_user_id            ON auth_sessions (user_id);
CREATE INDEX idx_auth_sessions_expires_at         ON auth_sessions (expires_at);
CREATE INDEX idx_orders_buyer_status              ON orders (buyer_business_id, status, created_at DESC);
CREATE INDEX idx_orders_wholesaler_status         ON orders (wholesaler_business_id, status, created_at DESC);
CREATE INDEX idx_order_items_order                ON order_items (order_id);
CREATE INDEX idx_invoices_order                   ON invoices (order_id);
CREATE INDEX idx_parcels_sender                   ON parcels (sender_id);
CREATE INDEX idx_parcels_receiver                 ON parcels (receiver_id);
CREATE INDEX idx_parcels_order                    ON parcels (order_id);
CREATE INDEX idx_tracking_parcel_time             ON tracking_logs (parcel_id, scanned_at DESC);
CREATE INDEX idx_tracking_courier                 ON tracking_logs (courier_id);
CREATE INDEX idx_notifications_user               ON notifications (user_id, created_at DESC);

-- ==========================================================================
-- SECTION 10 — Schema-level seed data
--
-- The 12 canonical categories, seeded by migration 005 (this table is the
-- single source for the taxonomy that once lived in SubNav.jsx). Demo rows
-- live in backend/seeds/dev_seed.sql, not here.
-- ==========================================================================

INSERT INTO categories (category_name) VALUES
    ('Pork'), ('Beef'), ('Chicken'), ('Chips'), ('Fish'), ('Shellfish'),
    ('Produce'), ('Bakery'), ('Dairy'), ('Frozen'), ('Packaging'), ('Beverages')
ON CONFLICT (category_name) DO NOTHING;

-- ==========================================================================
-- SECTION 11 — Migration bookkeeping
--
-- Stamp 001..024 as applied so `npm run migrate` on a database built from this
-- file runs only NEW migrations instead of replaying the whole history against
-- an already-final schema (which would fail on the first CREATE TABLE).
--
-- WHEN YOU ADD MIGRATION 025: add its filename to this list AND fold its
-- changes into the sections above, or this file drifts from the migrations.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS schema_migrations (
    filename   TEXT PRIMARY KEY,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_migrations (filename) VALUES
    ('001_initial_schema.sql'),
    ('002_logistics_schema.sql'),
    ('003_linko_schema.sql'),
    ('004_auth_rbac.sql'),
    ('005_marketplace_products.sql'),
    ('006_orders_invoices.sql'),
    ('007_logistics_expansion.sql'),
    ('008_couriers_user_id.sql'),
    ('009_parcels_order_link.sql'),
    ('010_timestamps.sql'),
    ('011_user_is_active.sql'),
    ('012_backfill_tracking_branch.sql'),
    ('013_orders_returned_status.sql'),
    ('014_repair_marketplace_parcel_pricing.sql'),
    ('015_logistics_soft_delete.sql'),
    ('016_logistics_constraints.sql'),
    ('017_phaseout_both_role.sql'),
    ('018_phaseout_commissions.sql'),
    ('019_phaseout_inventory_items.sql'),
    ('020_tracking_return_paths.sql'),
    ('021_out_for_return_status.sql'),
    ('022_couriers_single_org.sql'),
    ('023_location_routing.sql'),
    ('024_location_routing_constraints.sql')
ON CONFLICT (filename) DO NOTHING;

COMMIT;
